name: Go CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build Go application
      - name: Build Go application
        run: |
          go build -o go-ci-cd-app main.go
          zip go-ci-cd-app.zip go-ci-cd-app
          tar -czvf go-ci-cd-app.tar.gz go-ci-cd-app

      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/nava200/go-ci-cd-app:latest .
          docker push ghcr.io/nava200/go-ci-cd-app:latest

      # Create a Git tag for the release
      - name: Create Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.MYPROJECT_TOKEN }}

      # Upload artifacts to GitHub Releases
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go-ci-cd-app.zip
            go-ci-cd-app.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.MYPROJECT_TOKEN }}
